### ISSUE TITLE
Re-adapting makes changelings lose their bonus from absorbing another changeling

### ISSUE THREAD

**Issue by Ludox235** [Citadel-Station-13/Citadel-Station-13#11784]
## Round ID:
22458
## Reproduction:
Be changeling
Absorb another changeling
Get epic power from absorbing other changeling
Decide to re-adapt
Your bonus 5 evolution points are gone.
Your bonus chemical storage and regeneration is gone.
Your objective? Red.
Your status? Crying.

![image](https://user-images.githubusercontent.com/43365748/78850279-18f88c80-7a17-11ea-82f8-1194abd6ba00.png)
![image](https://user-images.githubusercontent.com/43365748/78850314-3299d400-7a17-11ea-9e9e-2d1ed19d625f.png)
![image](https://user-images.githubusercontent.com/43365748/78850333-3f1e2c80-7a17-11ea-97b1-810610669335.png)

**Comment by Akrilla** [comment]
yikes, scary to think how long that might of been in the game
