### ISSUE TITLE
Delete the fucking pickle gun now

### ISSUE THREAD

**Issue by Ludox235** [Citadel-Station-13/Citadel-Station-13#12794]
![Screenshot_1112](https://user-images.githubusercontent.com/43365748/87635484-6f284a80-c73f-11ea-8b80-bfaeef2930d2.png)

Delete it. Now.

**Comment by MrJWhit** [comment]
It's adminspawn only.

**Comment by DeusSepulchre** [comment]
Git mad

**Comment by Ludox235** [comment]
> 
> 
> It's adminspawn only.

I don't fucking care this is a mistake
