### ISSUE TITLE
TGUI Chat bugs

### ISSUE THREAD

**Issue by TripleShades** [Citadel-Station-13/Citadel-Station-13#15279]
Issue reported from  Round ID: 28709 (Citadel Station)

Reporting client version: 514.1568

Testmerge: #15244 

You can open multiple chat boxes by pressing the button over and over again.
The Me emote box doesn't auto-focus on typing.
You can resize the chat box but it doesn't resize the typing area to fit.

**Comment by rossark** [comment]
Ignore command straight up doesnt work either or open menu box same with suit sensors
