### ISSUE TITLE
Can't set jumpsuit sensors

### ISSUE THREAD

**Issue by AurSka** [Citadel-Station-13/Citadel-Station-13#15278]
## Reproduction:

Trying to set your sensors doesn't open the window, thus not letting you set your sensors.

**Comment by TripleShades** [comment]
#15244 tagging for related test-merge

**Comment by SandPoot** [comment]
Needs more info, such as game version

**Comment by SandPoot** [comment]
Nevermind, tested and windows simply do not show up, thanks for reporting.
